"use client";
import type * as Leaflet from "leaflet";
import type { Layer, Map as LeafletMap } from "leaflet";
import { useEffect,useMemo,useRef,useState } from "react";
const LOCAL_TARGET:[number,number]=[41.8382,-87.6331],BASEMAP="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",BASEMAP_ATTRIBUTION="&copy; OpenStreetMap contributors",FORECAST_STEP_MINUTES=15,FORECAST_WINDOW_MINUTES=360;
type MetaPayload={modelInitUtc:string|null};type ForecastLayer="precipitation"|"clouds";type RadarFrame={observedAt:string};type Motion="approaching"|"movingAway"|"passingNearby"|"stationaryOrUnclear"|"unknown";
function validTimeLabel(init:string|null,min:number){if(!init)return min===0?"Model analysis":`Forecast +${min} min`;return new Intl.DateTimeFormat("en-US",{timeZone:"America/Chicago",hour:"numeric",minute:"2-digit",timeZoneName:"short"}).format(new Date(Date.parse(init)+min*60000))}
function runLabel(init:string|null){return init?`Run ${new Intl.DateTimeFormat("en-US",{timeZone:"America/Chicago",hour:"numeric",minute:"2-digit",timeZoneName:"short"}).format(new Date(init))}`:"Latest HRRR run"}
function relativeLabel(m:number){if(m===0)return"Current";const h=Math.floor(m/60),r=m%60;return!h?`+${r} min`:!r?`+${h} hr`:`+${h} hr ${r} min`}
function iemRunId(v:string){const d=new Date(v);return`${d.getUTCFullYear()}${String(d.getUTCMonth()+1).padStart(2,"0")}${String(d.getUTCDate()).padStart(2,"0")}${String(d.getUTCHours()).padStart(2,"0")}00`}
export default function ForecastRadar(){
 const containerRef=useRef<HTMLDivElement>(null),mapRef=useRef<LeafletMap|null>(null),leafletRef=useRef<typeof Leaflet|null>(null),modelRef=useRef<Layer|null>(null),observedRef=useRef<Layer|null>(null);
 const [frameIndex,setFrameIndex]=useState(0),[playing,setPlaying]=useState(false),[forecastLayer,setForecastLayer]=useState<ForecastLayer>("precipitation"),[mapReady,setMapReady]=useState(false),[modelInitUtc,setModelInitUtc]=useState<string|null>(null),[latestObservedAt,setLatestObservedAt]=useState<string|null>(null),[motion,setMotion]=useState<Motion>("unknown"),[touchMap,setTouchMap]=useState(false),[mapInteraction,setMapInteraction]=useState(false),[viewRevision,setViewRevision]=useState(0);
 useEffect(()=>{let active=true;async function load(){try{const [m,r,t]=await Promise.all([fetch("/api/forecast-radar/meta",{cache:"no-store"}),fetch("/api/radar/frames",{cache:"no-store"}),fetch("/api/threat",{cache:"no-store"})]);const mp=(m.ok?await m.json():null) as MetaPayload|null;const rp=r.ok?await r.json() as {frames:RadarFrame[]}:null;const tp=t.ok?await t.json() as {evolution?:{motion?:Motion}}:null;if(active){setModelInitUtc(mp?.modelInitUtc??null);setLatestObservedAt(rp?.frames?.at(-1)?.observedAt??null);setMotion(tp?.evolution?.motion??"unknown")}}catch{}}void load();const timer=setInterval(load,60000);return()=>{active=false;clearInterval(timer)}},[]);
 const forecastMinutes=useMemo(()=>{const count=FORECAST_WINDOW_MINUTES/FORECAST_STEP_MINUTES+1;if(!modelInitUtc)return Array.from({length:count},(_,i)=>i*FORECAST_STEP_MINUTES);const age=Math.max(0,Math.floor((Date.now()-Date.parse(modelInitUtc))/(FORECAST_STEP_MINUTES*60000))*FORECAST_STEP_MINUTES),start=Math.min(age,720);return Array.from({length:count},(_,i)=>start+i*FORECAST_STEP_MINUTES)},[modelInitUtc]);
 useEffect(()=>{setFrameIndex(0);setPlaying(false)},[modelInitUtc]);
 useEffect(()=>{let active=true;void import("leaflet").then(module=>{if(!active||!containerRef.current||mapRef.current)return;const L=module.default;leafletRef.current=L;const map=L.map(containerRef.current,{zoomControl:true,attributionControl:true}).setView(LOCAL_TARGET,8);map.createPane("weather");map.getPane("weather")!.style.zIndex="400";map.getPane("weather")!.style.pointerEvents="none";map.createPane("nowcast");map.getPane("nowcast")!.style.zIndex="410";map.getPane("nowcast")!.style.pointerEvents="none";const isTouch=matchMedia("(pointer: coarse)").matches;if(isTouch)map.dragging.disable();setTouchMap(isTouch);L.tileLayer(BASEMAP,{maxZoom:19,attribution:BASEMAP_ATTRIBUTION}).addTo(map);L.circleMarker(LOCAL_TARGET,{radius:8,color:"#fff",weight:2,fillColor:"#ff4d67",fillOpacity:1}).bindTooltip("Bridgeport",{direction:"top"}).addTo(map);map.on("moveend zoomend",()=>setViewRevision(v=>v+1));mapRef.current=map;setMapReady(true)});return()=>{active=false;mapRef.current?.remove();mapRef.current=null}},[]);
 useEffect(()=>{if(!containerRef.current)return;const o=new ResizeObserver(e=>{const r=e[0]?.contentRect;if(!r||r.width<100||r.height<100)return;requestAnimationFrame(()=>{mapRef.current?.invalidateSize(false);setViewRevision(v=>v+1)})});o.observe(containerRef.current);return()=>o.disconnect()},[]);
 useEffect(()=>{const map=mapRef.current;if(!map||!touchMap)return;mapInteraction?map.dragging.enable():map.dragging.disable()},[mapInteraction,touchMap]);
 useEffect(()=>{const map=mapRef.current,L=leafletRef.current;if(!map||!L||!mapReady)return;const frameMinutes=forecastMinutes[frameIndex],relative=Math.max(0,frameMinutes-forecastMinutes[0]);if(modelRef.current&&map.hasLayer(modelRef.current))map.removeLayer(modelRef.current);if(observedRef.current&&map.hasLayer(observedRef.current))map.removeLayer(observedRef.current);modelRef.current=null;observedRef.current=null;
  if(forecastLayer==="precipitation"){if(!modelInitUtc)return;const frame=String(frameMinutes).padStart(4,"0"),run=iemRunId(modelInitUtc);const blendEnd=motion==="approaching"?90:motion==="movingAway"?30:60;const liveWeight=latestObservedAt&&relative<=blendEnd?Math.max(0,1-relative/blendEnd):0;const tile=L.tileLayer(`https://mesonet.agron.iastate.edu/cache/tile.py/1.0.0/hrrr::REFP-F${frame}-${run}/{z}/{x}/{y}.png`,{pane:"weather",opacity:.82,maxZoom:12,attribution:"HRRR via Iowa Environmental Mesonet"}).addTo(map);modelRef.current=tile;
   if(liveWeight>0&&latestObservedAt){const bounds=map.getBounds(),sw=L.CRS.EPSG3857.project(bounds.getSouthWest()),ne=L.CRS.EPSG3857.project(bounds.getNorthEast()),size=map.getSize(),scale=Math.max(1,Math.min(3,1800/size.x,1800/size.y));const params=new URLSearchParams({bbox:`${sw.x},${sw.y},${ne.x},${ne.y}`,width:String(Math.round(size.x*scale)),height:String(Math.round(size.y*scale)),time:latestObservedAt});const live=L.imageOverlay(`/api/radar/image?${params}`,bounds,{opacity:Math.max(.38,.68*liveWeight),pane:"nowcast",interactive:false}).addTo(map);observedRef.current=live}
   return()=>{if(modelRef.current===tile&&map.hasLayer(tile))map.removeLayer(tile);modelRef.current=null;if(observedRef.current&&map.hasLayer(observedRef.current))map.removeLayer(observedRef.current);observedRef.current=null}}
  if(!modelInitUtc)return;const bounds=map.getBounds(),sw=L.CRS.EPSG3857.project(bounds.getSouthWest()),ne=L.CRS.EPSG3857.project(bounds.getNorthEast()),size=map.getSize();if(size.x<100||size.y<100)return;const params=new URLSearchParams({bbox:`${sw.x},${sw.y},${ne.x},${ne.y}`,width:String(size.x),height:String(size.y),modelInitUtc,forecastMinutes:String(frameMinutes)});const image=L.imageOverlay(`/api/forecast-cloud/image?${params}`,bounds,{opacity:.9,pane:"weather",interactive:false}).addTo(map);modelRef.current=image;return()=>{if(map.hasLayer(image))map.removeLayer(image);if(modelRef.current===image)modelRef.current=null}
 },[forecastMinutes,frameIndex,forecastLayer,mapReady,modelInitUtc,latestObservedAt,motion,viewRevision]);
 useEffect(()=>{if(!playing||mapInteraction)return;const step=forecastLayer==="clouds"?4:1,interval=forecastLayer==="clouds"?1300:900,timer=setInterval(()=>setFrameIndex(i=>(i+step)%forecastMinutes.length),interval);return()=>clearInterval(timer)},[forecastMinutes.length,playing,mapInteraction,forecastLayer]);
 const frameMinutes=forecastMinutes[frameIndex],displayMinutes=forecastLayer==="clouds"?Math.round(frameMinutes/60)*60:frameMinutes,relativeMinutes=Math.max(0,displayMinutes-forecastMinutes[0]),nearTermBlend=forecastLayer==="precipitation"&&relativeMinutes<=(motion==="approaching"?90:motion==="movingAway"?30:60);const setLayer=(layer:ForecastLayer)=>{setPlaying(false);setForecastLayer(layer);if(layer==="clouds")setFrameIndex(Math.round(frameIndex/4)*4)};
 return <div className="forecastRadarPlayer"><div className="weatherLayerToggle"><button type="button" className={forecastLayer==="precipitation"?"active":""} onClick={()=>setLayer("precipitation")}>Precipitation</button><button type="button" className={forecastLayer==="clouds"?"active":""} onClick={()=>setLayer("clouds")}>Cloud Cover</button></div><div className="radarShell forecastRadarShell"><div ref={containerRef} className={`radarMap forecastRadarMap ${touchMap?(mapInteraction?"mapTouchActive":"mapTouchScroll"):""}`}/>{touchMap&&<button type="button" className="mapInteractionButton" onClick={()=>{if(!mapInteraction)setPlaying(false);setMapInteraction(v=>!v)}}>{mapInteraction?"Done":"Move map"}</button>}<div className="radarReadout"><strong>{validTimeLabel(modelInitUtc,displayMinutes)}</strong><span>{relativeLabel(relativeMinutes)} · {nearTermBlend?"Live radar + HRRR blend":"HRRR forecast"} · {runLabel(modelInitUtc)}</span></div></div><div className="radarControls"><button type="button" onClick={()=>setPlaying(v=>!v)}><span>{playing?"Ⅱ":"▶"}</span> {playing?"Pause":"Play"}</button><input type="range" min="0" max={forecastMinutes.length-1} value={frameIndex} step={forecastLayer==="clouds"?4:1} onChange={e=>{setPlaying(false);setFrameIndex(Number(e.target.value))}}/><button type="button" className="newestButton" onClick={()=>{setPlaying(false);setFrameIndex(forecastMinutes.length-1)}}>+6 hr</button></div><p className="radarSource">{forecastLayer==="precipitation"?"Short-term view overlays the latest NOAA MRMS observation on the newest HRRR forecast. The source radar and model fields are not moved or reshaped; the observed layer simply fades out as forecast time increases. Future frames remain forecast guidance.":"NOAA/NCEP HRRR total cloud cover via NOMADS · hourly cloud fields · model guidance"}</p></div>
}
