"use client";

import type * as Leaflet from "leaflet";
import type { Layer, Map as LeafletMap } from "leaflet";
import { useEffect, useMemo, useRef, useState } from "react";

const LOCAL_TARGET: [number, number] = [41.8382, -87.6331];
const BASEMAP = "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png";
const BASEMAP_ATTRIBUTION = "&copy; OpenStreetMap contributors";
const FORECAST_STEP_MINUTES = 15;
const FORECAST_WINDOW_MINUTES = 360;
type MetaPayload = { modelInitUtc: string | null };
type ForecastLayer = "precipitation" | "clouds";
function validTimeLabel(modelInitUtc:string|null,forecastMinutes:number){if(!modelInitUtc)return forecastMinutes===0?"Model analysis":`Forecast +${forecastMinutes} min`;const valid=new Date(Date.parse(modelInitUtc)+forecastMinutes*60000);return new Intl.DateTimeFormat("en-US",{timeZone:"America/Chicago",hour:"numeric",minute:"2-digit",timeZoneName:"short"}).format(valid)}
function runLabel(modelInitUtc:string|null){if(!modelInitUtc)return"Latest HRRR run";return`Run ${new Intl.DateTimeFormat("en-US",{timeZone:"America/Chicago",hour:"numeric",minute:"2-digit",timeZoneName:"short"}).format(new Date(modelInitUtc))}`}
function relativeLabel(minutes:number){if(minutes===0)return"Current";const h=Math.floor(minutes/60),m=minutes%60;if(!h)return`+${m} min`;if(!m)return`+${h} hr`;return`+${h} hr ${m} min`}
function forecastHourLabel(minutes:number){const h=Math.floor(minutes/60),m=minutes%60;return m?`${h}:${String(m).padStart(2,"0")}`:String(h)}
function iemRunId(value:string){const d=new Date(value);return`${d.getUTCFullYear()}${String(d.getUTCMonth()+1).padStart(2,"0")}${String(d.getUTCDate()).padStart(2,"0")}${String(d.getUTCHours()).padStart(2,"0")}00`}
export default function ForecastRadar(){
 const containerRef=useRef<HTMLDivElement>(null),mapRef=useRef<LeafletMap|null>(null),leafletRef=useRef<typeof Leaflet|null>(null),overlayRef=useRef<Layer|null>(null);
 const [frameIndex,setFrameIndex]=useState(0),[playing,setPlaying]=useState(false),[forecastLayer,setForecastLayer]=useState<ForecastLayer>("precipitation"),[mapReady,setMapReady]=useState(false),[modelInitUtc,setModelInitUtc]=useState<string|null>(null),[touchMap,setTouchMap]=useState(false),[mapInteraction,setMapInteraction]=useState(false),[viewRevision,setViewRevision]=useState(0);
 useEffect(()=>{let active=true;async function load(){try{const r=await fetch("/api/forecast-radar/meta",{cache:"no-store"});const p=(r.ok?await r.json():null) as MetaPayload|null;if(active)setModelInitUtc(p?.modelInitUtc??null)}catch{if(active)setModelInitUtc(null)}}void load();const timer=window.setInterval(load,60000);return()=>{active=false;clearInterval(timer)}},[]);
 const forecastMinutes=useMemo(()=>{const count=FORECAST_WINDOW_MINUTES/FORECAST_STEP_MINUTES+1;if(!modelInitUtc)return Array.from({length:count},(_,i)=>i*FORECAST_STEP_MINUTES);const age=Math.max(0,Math.floor((Date.now()-Date.parse(modelInitUtc))/(FORECAST_STEP_MINUTES*60000))*FORECAST_STEP_MINUTES),start=Math.min(age,720);return Array.from({length:count},(_,i)=>start+i*FORECAST_STEP_MINUTES)},[modelInitUtc]);
 useEffect(()=>{setFrameIndex(0);setPlaying(false)},[modelInitUtc]);
 useEffect(()=>{let active=true;void import("leaflet").then(module=>{if(!active||!containerRef.current||mapRef.current)return;const L=module.default;leafletRef.current=L;const map=L.map(containerRef.current,{zoomControl:true,attributionControl:true}).setView(LOCAL_TARGET,8);map.createPane("weather");map.getPane("weather")!.style.zIndex="400";map.getPane("weather")!.style.pointerEvents="none";const isTouch=window.matchMedia("(pointer: coarse)").matches;if(isTouch)map.dragging.disable();setTouchMap(isTouch);L.tileLayer(BASEMAP,{maxZoom:19,attribution:BASEMAP_ATTRIBUTION}).addTo(map);L.circleMarker(LOCAL_TARGET,{radius:8,color:"#fff",weight:2,fillColor:"#ff4d67",fillOpacity:1}).bindTooltip("Bridgeport",{direction:"top"}).addTo(map);map.on("moveend zoomend",()=>setViewRevision(v=>v+1));mapRef.current=map;setMapReady(true)});return()=>{active=false;mapRef.current?.remove();mapRef.current=null}},[]);
 useEffect(()=>{if(!containerRef.current)return;const o=new ResizeObserver(entries=>{const r=entries[0]?.contentRect;if(!r||r.width<100||r.height<100)return;requestAnimationFrame(()=>{const map=mapRef.current;if(!map)return;map.invalidateSize(false);setViewRevision(v=>v+1)})});o.observe(containerRef.current);return()=>o.disconnect()},[]);
 useEffect(()=>{const map=mapRef.current;if(!map||!touchMap)return;if(mapInteraction)map.dragging.enable();else map.dragging.disable()},[mapInteraction,touchMap]);
 useEffect(()=>{const map=mapRef.current,L=leafletRef.current;if(!map||!L||!mapReady)return;const frameMinutes=forecastMinutes[frameIndex],previous=overlayRef.current;let next:Layer;let opacity:number;
  if(forecastLayer==="precipitation"){if(!modelInitUtc)return;const frame=String(frameMinutes).padStart(4,"0"),run=iemRunId(modelInitUtc);const url=`https://mesonet.agron.iastate.edu/cache/tile.py/1.0.0/hrrr::REFP-F${frame}-${run}/{z}/{x}/{y}.png`;const tile=L.tileLayer(url,{pane:"weather",opacity:0,maxZoom:12,attribution:"HRRR via Iowa Environmental Mesonet"}).addTo(map);next=tile;opacity=.62;let promoted=false;const promote=()=>{if(promoted)return;promoted=true;tile.setOpacity(opacity);overlayRef.current=tile;if(previous&&previous!==tile&&map.hasLayer(previous))map.removeLayer(previous)};tile.once("load",promote);const fallback=window.setTimeout(promote,1200);return()=>{clearTimeout(fallback);tile.off("load",promote);if(overlayRef.current!==tile&&map.hasLayer(tile))map.removeLayer(tile)}}
  const bounds=map.getBounds(),sw=L.CRS.EPSG3857.project(bounds.getSouthWest()),ne=L.CRS.EPSG3857.project(bounds.getNorthEast()),size=map.getSize();if(size.x<100||size.y<100||!modelInitUtc)return;const params=new URLSearchParams({bbox:`${sw.x},${sw.y},${ne.x},${ne.y}`,width:String(size.x),height:String(size.y),modelInitUtc,forecastMinutes:String(frameMinutes)});const image=L.imageOverlay(`/api/forecast-cloud/image?${params}`,bounds,{opacity:0,pane:"weather",interactive:false}).addTo(map);next=image;opacity=.82;let promoted=false;const promote=()=>{if(promoted)return;promoted=true;image.setOpacity(opacity);overlayRef.current=image;if(previous&&previous!==image&&map.hasLayer(previous))map.removeLayer(previous)};const discard=()=>{if(map.hasLayer(image))map.removeLayer(image)};image.once("load",promote);image.once("error",discard);return()=>{image.off("load",promote);image.off("error",discard);if(overlayRef.current!==next&&map.hasLayer(next))map.removeLayer(next)}
 },[forecastMinutes,frameIndex,forecastLayer,mapReady,modelInitUtc,viewRevision]);
 useEffect(()=>{if(!playing||mapInteraction)return;const step=forecastLayer==="clouds"?4:1,interval=forecastLayer==="clouds"?1300:900;const timer=setInterval(()=>setFrameIndex(i=>(i+step)%forecastMinutes.length),interval);return()=>clearInterval(timer)},[forecastMinutes.length,playing,mapInteraction,forecastLayer]);
 const frameMinutes=forecastMinutes[frameIndex],cloudFrameMinutes=Math.round(frameMinutes/60)*60,displayMinutes=forecastLayer==="clouds"?cloudFrameMinutes:frameMinutes,relativeMinutes=Math.max(0,displayMinutes-forecastMinutes[0]);
 const setLayer=(layer:ForecastLayer)=>{setPlaying(false);setForecastLayer(layer);if(layer==="clouds")setFrameIndex(Math.round(frameIndex/4)*4)};const toggleMapInteraction=()=>{if(!mapInteraction)setPlaying(false);setMapInteraction(v=>!v)};
 return <div className="forecastRadarPlayer"><div className="weatherLayerToggle" role="group" aria-label="Forecast weather layer"><button type="button" className={forecastLayer==="precipitation"?"active":""} onClick={()=>setLayer("precipitation")}>Precipitation</button><button type="button" className={forecastLayer==="clouds"?"active":""} onClick={()=>setLayer("clouds")}>Cloud Cover</button></div><div className="radarShell forecastRadarShell"><div ref={containerRef} className={`radarMap forecastRadarMap ${touchMap?(mapInteraction?"mapTouchActive":"mapTouchScroll"):""}`} aria-label={`HRRR six-hour ${forecastLayer==="precipitation"?"simulated reflectivity":"total cloud cover"} forecast centered on Bridgeport, Chicago`}/>{touchMap&&<button type="button" className="mapInteractionButton" onClick={toggleMapInteraction}>{mapInteraction?"Done":"Move map"}</button>}<div className="radarReadout" aria-live="polite"><strong>{validTimeLabel(modelInitUtc,displayMinutes)}</strong><span>{relativeLabel(relativeMinutes)} · HRRR F+{forecastHourLabel(displayMinutes)} · {runLabel(modelInitUtc)}</span></div></div><div className="radarControls"><button type="button" onClick={()=>setPlaying(v=>!v)}><span aria-hidden="true">{playing?"Ⅱ":"▶"}</span> {playing?"Pause":"Play"}</button><input type="range" min="0" max={forecastMinutes.length-1} value={frameIndex} step={forecastLayer==="clouds"?4:1} onChange={e=>{setPlaying(false);setFrameIndex(Number(e.target.value))}} aria-label="Forecast timeline"/><button type="button" className="newestButton" onClick={()=>{setPlaying(false);setFrameIndex(forecastMinutes.length-1)}} disabled={frameIndex===forecastMinutes.length-1&&!playing}>+6 hr</button></div><p className="radarSource">{forecastLayer==="precipitation"?"NCEP HRRR simulated reflectivity at 1 km AGL via Iowa Environmental Mesonet · frames locked to the displayed HRRR run · 15-minute forecast increments · model guidance, not observed radar":"NOAA/NCEP HRRR total cloud cover (TCDC) via NOMADS · hourly cloud fields on the same six-hour forecast window · model guidance"}</p></div>
}
