import "server-only";

const NWS_BASE = "https://api.weather.gov";
const USER_AGENT = "BridgeportStormWatch (https://bridgeport-weather.vercel.app)";

export type NwsAlertSeverity = "Extreme" | "Severe" | "Moderate" | "Minor" | "Unknown";
export type NwsAlert = { id: string; event: string; headline: string | null; severity: NwsAlertSeverity; urgency: string; areaDesc: string; effective: string; expires: string; coversPoint: boolean | null; approxDistanceMiles: number | null };
type GeoJsonGeometry = { type: string; coordinates: unknown } | null;
type NwsFeature = { id: string; properties: { event?: string; headline?: string | null; severity?: string; urgency?: string; areaDesc?: string; effective?: string; expires?: string }; geometry: GeoJsonGeometry };
function toSeverity(value: string | undefined): NwsAlertSeverity { if (value === "Extreme" || value === "Severe" || value === "Moderate" || value === "Minor") return value; return "Unknown"; }
function pointInRing(lat: number, lon: number, ring: number[][]): boolean { let inside = false; for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) { const [xi, yi] = ring[i]; const [xj, yj] = ring[j]; const intersects = yi > lat !== yj > lat && lon < ((xj - xi) * (lat - yi)) / (yj - yi) + xi; if (intersects) inside = !inside; } return inside; }
function polygonCoversPoint(geometry: GeoJsonGeometry, lat: number, lon: number): boolean { if (!geometry) return false; if (geometry.type === "Polygon") { const rings = geometry.coordinates as number[][][]; return rings.length > 0 && pointInRing(lat, lon, rings[0]); } if (geometry.type === "MultiPolygon") { const polygons = geometry.coordinates as number[][][][]; return polygons.some((rings) => rings.length > 0 && pointInRing(lat, lon, rings[0])); } return false; }
function haversineMiles(lat1: number, lon1: number, lat2: number, lon2: number): number { const R = 3958.8; const toRad = (deg: number) => (deg * Math.PI) / 180; const dLat = toRad(lat2 - lat1); const dLon = toRad(lon2 - lon1); const a = Math.sin(dLat / 2) ** 2 + Math.cos(toRad(lat1)) * Math.cos(toRad(lat2)) * Math.sin(dLon / 2) ** 2; return 2 * R * Math.asin(Math.sqrt(a)); }
function approxDistanceToGeometry(geometry: GeoJsonGeometry, lat: number, lon: number): number | null { if (!geometry) return null; const rings: number[][][] = geometry.type === "Polygon" ? (geometry.coordinates as number[][][]) : geometry.type === "MultiPolygon" ? (geometry.coordinates as number[][][][]).flat() : []; let min = Infinity; for (const ring of rings) for (const [vLon, vLat] of ring) min = Math.min(min, haversineMiles(lat, lon, vLat, vLon)); return Number.isFinite(min) ? min : null; }
async function fetchAlerts(url: string): Promise<NwsFeature[]> { const response = await fetch(url, { headers: { "User-Agent": USER_AGENT, Accept: "application/geo+json" }, next: { revalidate: 60 } }); if (!response.ok) throw new Error(`NWS alerts request failed: ${response.status}`); const payload = await response.json(); return Array.isArray(payload?.features) ? payload.features : []; }
function toAlert(feature: NwsFeature, lat: number, lon: number): NwsAlert { const hasGeometry = Boolean(feature.geometry); const covers = hasGeometry ? polygonCoversPoint(feature.geometry, lat, lon) : null; return { id: feature.id, event: feature.properties.event ?? "Alert", headline: feature.properties.headline ?? null, severity: toSeverity(feature.properties.severity), urgency: feature.properties.urgency ?? "Unknown", areaDesc: feature.properties.areaDesc ?? "", effective: feature.properties.effective ?? "", expires: feature.properties.expires ?? "", coversPoint: covers, approxDistanceMiles: covers ? 0 : approxDistanceToGeometry(feature.geometry, lat, lon) }; }
const IGNORED_EVENT_TYPES = new Set(["Beach Hazards Statement"]);
const NEARBY_EVENT_TYPES = new Set(["Tornado Warning", "Tornado Watch", "Severe Thunderstorm Warning", "Severe Thunderstorm Watch", "Flash Flood Warning"]);
const NEARBY_RADIUS_MILES = 40;
export type NwsAlertsResult = { here: NwsAlert[]; nearby: NwsAlert[] };
export async function getNwsAlerts(lat: number, lon: number, stateCode: string): Promise<NwsAlertsResult> { const pointUrl = `${NWS_BASE}/alerts/active?point=${lat},${lon}`; const areaUrl = `${NWS_BASE}/alerts/active/area/${stateCode}`; const [pointFeatures, areaFeatures] = await Promise.all([fetchAlerts(pointUrl), fetchAlerts(areaUrl)]); const here = pointFeatures.filter((feature) => !IGNORED_EVENT_TYPES.has(feature.properties.event ?? "")).map((feature) => toAlert(feature, lat, lon)); const hereIds = new Set(here.map((alert) => alert.id)); const nearby = areaFeatures.filter((feature) => !hereIds.has(feature.id)).filter((feature) => NEARBY_EVENT_TYPES.has(feature.properties.event ?? "")).map((feature) => toAlert(feature, lat, lon)).filter((alert) => alert.approxDistanceMiles !== null && alert.approxDistanceMiles <= NEARBY_RADIUS_MILES).sort((a, b) => (a.approxDistanceMiles ?? Infinity) - (b.approxDistanceMiles ?? Infinity)); return { here, nearby }; }
