import type { NwsAlert } from "./nws";
import type { StormTrend } from "./evolution";
export type ThreatLevel = "none" | "monitor" | "elevated" | "severe";
export type ThreatCategory = "wind" | "hail" | "heavyRain" | "tornado" | "officialWarning" | "radarCore";
export type ThreatFactor = { category: ThreatCategory; level: ThreatLevel; headline: string; detail: string };
export type ThreatAssessment = { overallLevel: ThreatLevel; factors: ThreatFactor[]; generatedAt: string };
export type ThreatInput = { windGustMph:number|null; hourlyRainIn:number|null; radarDbz:number|null; strongestNearbyDbz:number|null; stormTrend:StormTrend|null; pressureTrendInHgPerHr:number|null; alertsHere:NwsAlert[]; alertsNearby:NwsAlert[] };
const RANK:Record<ThreatLevel,number>={none:0,monitor:1,elevated:2,severe:3};
const higher=(a:ThreatLevel,b:ThreatLevel):ThreatLevel=>RANK[a]>=RANK[b]?a:b;
function wind(v:number|null):ThreatFactor{if(v===null)return{category:"wind",level:"none",headline:"Wind: no data",detail:"Live gust reading is unavailable."};if(v>=58)return{category:"wind",level:"elevated",headline:"Very strong local gust",detail:`Station gust ${v.toFixed(0)} mph. The exposed deck installation can read high, so this is a local verification signal and does not by itself establish severe weather.`};if(v>=40)return{category:"wind",level:"elevated",headline:"Strong, gusty wind",detail:`Station gust ${v.toFixed(0)} mph.`};if(v>=25)return{category:"wind",level:"monitor",headline:"Breezy to gusty",detail:`Station gust ${v.toFixed(0)} mph.`};return{category:"wind",level:"none",headline:"Wind: nominal",detail:`Station gust ${v.toFixed(0)} mph.`}}
function hail(v:number|null):ThreatFactor{if(v===null)return{category:"hail",level:"none",headline:"Hail: no radar data",detail:"Point reflectivity is unavailable."};if(v>=55)return{category:"hail",level:"elevated",headline:"Hail possible in intense core",detail:`Reflectivity ${v.toFixed(0)} dBZ is intense enough for hail to be possible, but reflectivity alone cannot confirm hail or severe size.`};if(v>=48)return{category:"hail",level:"monitor",headline:"Hail cannot be ruled out",detail:`Reflectivity ${v.toFixed(0)} dBZ indicates a strong core; heavy rain may be the primary cause.`};return{category:"hail",level:"none",headline:"Hail: not indicated",detail:v>0?`Reflectivity ${v.toFixed(0)} dBZ does not by itself indicate a severe hail threat.`:"No significant echo overhead."}}
function rain(v:number|null):ThreatFactor{if(v===null)return{category:"heavyRain",level:"none",headline:"Rain: no data",detail:"Live rain-rate reading is unavailable."};if(v>=2)return{category:"heavyRain",level:"elevated",headline:"Very heavy local rain",detail:`Station rain rate ${v.toFixed(2)} in/hr. Gauge exposure can affect this reading; heavy rain alone is not classified as severe weather.`};if(v>=1)return{category:"heavyRain",level:"monitor",headline:"Heavy local rain",detail:`Station rain rate ${v.toFixed(2)} in/hr; gauge exposure can affect this reading.`};if(v>=.3)return{category:"heavyRain",level:"monitor",headline:"Moderate local rain",detail:`Station rain rate ${v.toFixed(2)} in/hr.`};return{category:"heavyRain",level:"none",headline:"Rain: light or none",detail:v>0?`Rain rate ${v.toFixed(2)} in/hr.`:"No rain currently detected at the station."}}
function radarCore(local:number|null,nearby:number|null,trend:StormTrend|null):ThreatFactor{const strongest=Math.max(local??-Infinity,nearby??-Infinity);if(!Number.isFinite(strongest))return{category:"radarCore",level:"none",headline:"Radar core: unavailable",detail:"Current MRMS intensity sampling is unavailable."};const trendText=trend&&trend!=="unknown"?` Recent samples are ${trend}.`:"";if(strongest>=55)return{category:"radarCore",level:"elevated",headline:"Intense convective core nearby",detail:`MRMS reflectivity reaches about ${strongest.toFixed(0)} dBZ in the local sample.${trendText} This can represent torrential rain and/or hail, but reflectivity alone does not establish severe weather.`};if(strongest>=45)return{category:"radarCore",level:trend==="strengthening"?"elevated":"monitor",headline:trend==="strengthening"?"Strong core is strengthening":"Strong convective echo nearby",detail:`Local MRMS reflectivity reaches about ${strongest.toFixed(0)} dBZ.${trendText} Monitor for official warnings and rapid local changes.`};if(strongest>=30)return{category:"radarCore",level:"monitor",headline:"Rain/storm echo near Bridgeport",detail:`Local MRMS reflectivity reaches about ${strongest.toFixed(0)} dBZ.${trendText} This is not a severe classification.`};return{category:"radarCore",level:"none",headline:"Radar: no significant convective core",detail:"No strong MRMS core is currently sampled over or near Bridgeport."}}
function tornado(h:NwsAlert[],n:NwsAlert[]):ThreatFactor{const here=h.find(a=>a.event==="Tornado Warning");if(here)return{category:"tornado",level:"severe",headline:"TORNADO WARNING for Bridgeport",detail:"An active NWS Tornado Warning includes the Bridgeport point. Follow official warning instructions and take shelter."};const near=n.find(a=>a.event==="Tornado Warning");if(near)return{category:"tornado",level:"elevated",headline:"Tornado Warning nearby",detail:`An active NWS Tornado Warning is nearby${near.approxDistanceMiles!==null?` (~${near.approxDistanceMiles.toFixed(0)} mi)`:""}, but does not currently include Bridgeport.`};const watch=h.find(a=>a.event==="Tornado Watch")||n.find(a=>a.event==="Tornado Watch");if(watch)return{category:"tornado",level:"monitor",headline:"Tornado Watch in the area",detail:"Conditions are favorable for tornadoes. Monitor official NWS warnings."};return{category:"tornado",level:"none",headline:"No active tornado warning",detail:"Reflectivity alone cannot detect rotation; tornado status comes from official NWS alerts."}}
function official(h:NwsAlert[],n:NwsAlert[]):ThreatFactor{const events=new Set(["Severe Thunderstorm Warning","Flash Flood Warning"]);const here=h.find(a=>events.has(a.event));if(here)return{category:"officialWarning",level:"severe",headline:`${here.event} for Bridgeport`,detail:"An active official NWS warning includes the Bridgeport point."};const near=n.find(a=>events.has(a.event));if(near)return{category:"officialWarning",level:"elevated",headline:`${near.event} nearby`,detail:`An active warning is nearby${near.approxDistanceMiles!==null?` (~${near.approxDistanceMiles.toFixed(0)} mi)`:""} but does not currently include Bridgeport.`};const watch=h.find(a=>a.event==="Severe Thunderstorm Watch")||n.find(a=>a.event==="Severe Thunderstorm Watch");if(watch)return{category:"officialWarning",level:"monitor",headline:"Severe Thunderstorm Watch in the area",detail:"Conditions are favorable for severe thunderstorms."};return{category:"officialWarning",level:"none",headline:"No official severe warnings",detail:"No Tornado, Severe Thunderstorm, or Flash Flood Warning currently affects Bridgeport."}}
export function assessThreat(i:ThreatInput):ThreatAssessment{const factors=[official(i.alertsHere,i.alertsNearby),tornado(i.alertsHere,i.alertsNearby),radarCore(i.radarDbz,i.strongestNearbyDbz,i.stormTrend),hail(i.radarDbz),wind(i.windGustMph),rain(i.hourlyRainIn)];return{overallLevel:factors.reduce((a,f)=>higher(a,f.level),"none" as ThreatLevel),factors,generatedAt:new Date().toISOString()}}
