import type { NwsAlert } from "./nws";
import type { StormTrend, StormMotion } from "./evolution";
import type { ProbSevereStorm } from "./probsevere";
export type ThreatLevel = "none" | "monitor" | "elevated" | "severe";
export type ThreatCategory = "wind" | "hail" | "heavyRain" | "tornado" | "officialWarning" | "radarCore" | "probSevere";
export type ThreatFactor = { category: ThreatCategory; level: ThreatLevel; headline: string; detail: string };
export type ThreatAssessment = { overallLevel: ThreatLevel; factors: ThreatFactor[]; generatedAt: string };
export type ThreatInput = { windGustMph:number|null; hourlyRainIn:number|null; radarDbz:number|null; strongestNearbyDbz:number|null; stormTrend:StormTrend|null; stormMotion?:StormMotion|null; pressureTrendInHgPerHr:number|null; alertsHere:NwsAlert[]; alertsNearby:NwsAlert[]; probSevereStorm:ProbSevereStorm|null };
const RANK:Record<ThreatLevel,number>={none:0,monitor:1,elevated:2,severe:3};
const higher=(a:ThreatLevel,b:ThreatLevel):ThreatLevel=>RANK[a]>=RANK[b]?a:b;
function wind(v:number|null):ThreatFactor{if(v===null)return{category:"wind",level:"none",headline:"Wind: no data",detail:"Live gust reading is unavailable."};if(v>=58)return{category:"wind",level:"elevated",headline:"Very strong local gust",detail:`Station gust ${v.toFixed(0)} mph. This is a local verification signal and does not by itself establish severe weather.`};if(v>=40)return{category:"wind",level:"elevated",headline:"Strong, gusty wind",detail:`Station gust ${v.toFixed(0)} mph.`};if(v>=25)return{category:"wind",level:"monitor",headline:"Breezy to gusty",detail:`Station gust ${v.toFixed(0)} mph.`};return{category:"wind",level:"none",headline:"Wind: nominal",detail:`Station gust ${v.toFixed(0)} mph.`}}
function hail(v:number|null,corroborated:boolean):ThreatFactor{if(v===null)return{category:"hail",level:"none",headline:"Hail: no radar data",detail:"Point reflectivity is unavailable."};if(v>=55&&corroborated)return{category:"hail",level:"elevated",headline:"Hail possible in strong storm",detail:"A strong radar echo over Bridgeport is supported by other local severe-weather evidence. Hail is possible, but radar alone cannot confirm it."};if(v>=55)return{category:"hail",level:"none",headline:"No confirmed hail signal",detail:"A high radar sample is not supported by the local rain gauge, wind observations, official warnings, or ProbSevere, so it is not being treated as a hail threat."};if(v>=48&&corroborated)return{category:"hail",level:"monitor",headline:"Hail cannot be ruled out",detail:"A strong radar echo is supported by other local storm evidence."};return{category:"hail",level:"none",headline:"Hail: not indicated",detail:"Current local observations do not indicate a hail threat."}}
function rain(v:number|null):ThreatFactor{if(v===null)return{category:"heavyRain",level:"none",headline:"Rain: no data",detail:"Live rain-rate reading is unavailable."};if(v>=2)return{category:"heavyRain",level:"elevated",headline:"Very heavy local rain",detail:`Station rain rate ${v.toFixed(2)} in/hr.`};if(v>=1)return{category:"heavyRain",level:"monitor",headline:"Heavy local rain",detail:`Station rain rate ${v.toFixed(2)} in/hr.`};if(v>=.3)return{category:"heavyRain",level:"monitor",headline:"Moderate local rain",detail:`Station rain rate ${v.toFixed(2)} in/hr.`};return{category:"heavyRain",level:"none",headline:"Rain: light or none",detail:v>0?`Rain rate ${v.toFixed(2)} in/hr.`:"No rain currently detected at the station."}}
function radarCore(local:number|null,nearby:number|null,trend:StormTrend|null,motion:StormMotion|null|undefined,corroborated:boolean):ThreatFactor{const strongest=Math.max(local??-Infinity,nearby??-Infinity);if(!Number.isFinite(strongest))return{category:"radarCore",level:"none",headline:"Radar unavailable",detail:"Current radar intensity is unavailable."};const movingAway=motion==="movingAway"&&(local??0)<35;if(movingAway&&strongest>=30)return{category:"radarCore",level:"none",headline:"Storm moving away from Bridgeport",detail:"Radar shows a storm nearby, but it is moving away from our area."};if((local??0)>=45&&!corroborated)return{category:"radarCore",level:"monitor",headline:"Radar echo over Bridgeport",detail:"Radar is sampling a strong echo near Bridgeport, but the local station is dry and there is no supporting official warning or ProbSevere signal. Monitoring for confirmation."};if(strongest>=55&&corroborated)return{category:"radarCore",level:"elevated",headline:"Strong storm affecting Bridgeport",detail:`Radar shows a strong storm near Bridgeport${trend&&trend!=="unknown"?` that is ${trend}`:""}, supported by other local storm evidence.`};if(strongest>=45&&corroborated)return{category:"radarCore",level:"monitor",headline:"Strong storm nearby",detail:"Radar and other local evidence support a strong storm near Bridgeport."};if(strongest>=30)return{category:"radarCore",level:"monitor",headline:"Rain or storm nearby",detail:"Radar shows scattered rain or a storm near Bridgeport. Local observations do not currently indicate a significant impact."};return{category:"radarCore",level:"none",headline:"No significant storm nearby",detail:"No strong storm is currently affecting Bridgeport."}}
function probSevere(storm:ProbSevereStorm|null):ThreatFactor{if(!storm)return{category:"probSevere",level:"none",headline:"ProbSevere: no nearby tracked storm",detail:"NOAA ProbSevere has no storm object within about 30 miles of Bridgeport right now."};const ps=storm.probSevere??0;const highestHazard=Math.max(storm.probHail??0,storm.probWind??0,storm.probTor??0);const level:ThreatLevel=ps>=50||highestHazard>=40?"elevated":ps>=20||highestHazard>=20?"monitor":"none";const parts=[storm.probHail!==null?`hail ${storm.probHail.toFixed(0)}%`:null,storm.probWind!==null?`wind ${storm.probWind.toFixed(0)}%`:null,storm.probTor!==null?`tornado ${storm.probTor.toFixed(0)}%`:null].filter(Boolean).join(" · ");return{category:"probSevere",level,headline:level==="elevated"?"ProbSevere indicates elevated severe potential":level==="monitor"?"ProbSevere storm nearby":"ProbSevere severe signal is low",detail:`Closest relevant ProbSevere storm object is about ${storm.distanceMiles.toFixed(0)} mi from Bridgeport with overall severe probability ${ps.toFixed(0)}%${parts?` (${parts})`:""}. This is NOAA guidance, not an official warning.`}}
function tornado(h:NwsAlert[],n:NwsAlert[]):ThreatFactor{const here=h.find(a=>a.event==="Tornado Warning");if(here)return{category:"tornado",level:"severe",headline:"TORNADO WARNING for Bridgeport",detail:"An active NWS Tornado Warning includes Bridgeport. Follow official warning instructions and take shelter."};const near=n.find(a=>a.event==="Tornado Warning");if(near)return{category:"tornado",level:"elevated",headline:"Tornado Warning nearby",detail:`An active NWS Tornado Warning is nearby${near.approxDistanceMiles!==null?` (~${near.approxDistanceMiles.toFixed(0)} mi)`:""}, but does not currently include Bridgeport.`};const watch=h.find(a=>a.event==="Tornado Watch")||n.find(a=>a.event==="Tornado Watch");if(watch)return{category:"tornado",level:"monitor",headline:"Tornado Watch in the area",detail:"Conditions are favorable for tornadoes. Monitor official NWS warnings."};return{category:"tornado",level:"none",headline:"No active tornado warning",detail:"No active official tornado warning affects Bridgeport."}}
function official(h:NwsAlert[],n:NwsAlert[]):ThreatFactor{const events=new Set(["Severe Thunderstorm Warning","Flash Flood Warning"]);const here=h.find(a=>events.has(a.event));if(here)return{category:"officialWarning",level:"severe",headline:`${here.event} for Bridgeport`,detail:"An active official NWS warning includes Bridgeport."};const near=n.find(a=>events.has(a.event));if(near)return{category:"officialWarning",level:"elevated",headline:`${near.event} nearby`,detail:`An active warning is nearby${near.approxDistanceMiles!==null?` (~${near.approxDistanceMiles.toFixed(0)} mi)`:""} but does not currently include Bridgeport.`};const watch=h.find(a=>a.event==="Severe Thunderstorm Watch")||n.find(a=>a.event==="Severe Thunderstorm Watch");if(watch)return{category:"officialWarning",level:"monitor",headline:"Severe Thunderstorm Watch in the area",detail:"Conditions are favorable for severe thunderstorms."};return{category:"officialWarning",level:"none",headline:"No official severe warnings",detail:"No Tornado, Severe Thunderstorm, or Flash Flood Warning currently affects Bridgeport."}}
export function assessThreat(i:ThreatInput):ThreatAssessment{const officialSignal=i.alertsHere.some(a=>["Tornado Warning","Severe Thunderstorm Warning","Flash Flood Warning"].includes(a.event));const probSignal=(i.probSevereStorm?.probSevere??0)>=20||Math.max(i.probSevereStorm?.probHail??0,i.probSevereStorm?.probWind??0,i.probSevereStorm?.probTor??0)>=20;const stationSignal=(i.hourlyRainIn??0)>=.05||(i.windGustMph??0)>=25;const corroborated=officialSignal||probSignal||stationSignal;const factors=[official(i.alertsHere,i.alertsNearby),tornado(i.alertsHere,i.alertsNearby),probSevere(i.probSevereStorm),radarCore(i.radarDbz,i.strongestNearbyDbz,i.stormTrend,i.stormMotion,corroborated),hail(i.radarDbz,corroborated),wind(i.windGustMph),rain(i.hourlyRainIn)];return{overallLevel:factors.reduce((a,f)=>higher(a,f.level),"none" as ThreatLevel),factors,generatedAt:new Date().toISOString()}}
